import type { Property } from "./types";

// Seeded from MASTER LOG CSV. Stages inferred from closing/completion dates
// relative to 2026-04-15. JV Split intentionally omitted per spec.
// NOTE: The CSV had "25-Jan-06" for 5501 Ball Road — corrected to 2026-01-25.

const now = "2026-04-15T00:00:00.000Z";

export const SEED_PROPERTIES: Property[] = [
  {
    id: "prop_ball_road",
    address: "5501 Ball Road, Knoxville, TN",
    stage: "in_rehab",
    lender: "Approach Lending",
    interestRate: 0.1199,
    closingDate: "2026-01-25",
    sellerTitleCompany: "Superior",
    buyerTitleCompany: "Superior",
    purchasePrice: 215000,
    rehabBudget: 120000,
    earnestMoney: 4000,
    downPayment: 55000,
    totalLoanAmount: 280000,
    origFee: 8400,
    loanFee: 799,
    acquisitionFee: 0,
    financeFee: 0,
    closingCosts: 5160,
    neededAtClosing: 69359,
    ioPayments: 25179,
    projectedSalePrice: 500000,
    projectedProfitFromSale: 125462,
    projectedProfitFromRehab: 24000,
    totalProjectedProfit: 149462,
    investedCapital: 39538,
    equityMultiple: 4.78,
    projectedCompletionDate: "2026-06-25",
    soldDate: null,
    soldPrice: null,
    notes: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prop_inskip",
    address: "705 W Inskip Drive, Knoxville, TN",
    stage: "in_rehab",
    lender: "Approach Lending",
    interestRate: 0.1199,
    closingDate: "2026-02-16",
    sellerTitleCompany: "Good Deeds",
    buyerTitleCompany: "Good Deeds",
    purchasePrice: 120000,
    rehabBudget: 61500,
    earnestMoney: 1000,
    downPayment: 24000,
    totalLoanAmount: 157500,
    origFee: 4725,
    loanFee: 799,
    acquisitionFee: 0,
    financeFee: 0,
    closingCosts: 1969,
    neededAtClosing: 31493,
    ioPayments: 9313,
    projectedSalePrice: 225000,
    projectedProfitFromSale: 26694,
    projectedProfitFromRehab: 12300,
    totalProjectedProfit: 38994,
    investedCapital: 16806,
    equityMultiple: 3.32,
    projectedCompletionDate: "2026-07-01",
    soldDate: null,
    soldPrice: null,
    notes: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prop_jacksboro",
    address: "5536 Jacksboro Pike, Knoxville, TN",
    stage: "in_rehab",
    lender: "Tier 1 Capital",
    interestRate: 0.085,
    closingDate: "2026-04-01",
    sellerTitleCompany: "Foothills",
    buyerTitleCompany: "Foothills",
    purchasePrice: 140000,
    rehabBudget: 174900,
    earnestMoney: 2500,
    downPayment: 33700,
    totalLoanAmount: 281200,
    origFee: 1209,
    loanFee: 1205,
    acquisitionFee: 15000,
    financeFee: 0,
    closingCosts: 3266,
    neededAtClosing: 37823,
    ioPayments: 11787,
    projectedSalePrice: 400000,
    projectedProfitFromSale: 52632,
    projectedProfitFromRehab: 34980,
    totalProjectedProfit: 87612,
    investedCapital: 32468,
    equityMultiple: 3.7,
    projectedCompletionDate: "2026-11-01",
    soldDate: null,
    soldPrice: null,
    notes: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prop_bennington",
    address: "7624 Bennington, Knoxville, TN 37909",
    stage: "in_rehab",
    lender: "Tier 1 Capital",
    interestRate: 0.085,
    closingDate: "2026-04-08",
    sellerTitleCompany: "Southeast",
    buyerTitleCompany: "Good Deeds",
    purchasePrice: 495000,
    rehabBudget: 140000,
    earnestMoney: 10000,
    downPayment: 68399,
    totalLoanAmount: 566601,
    origFee: 2609,
    loanFee: 1195,
    acquisitionFee: 15000,
    financeFee: 0,
    closingCosts: 6299,
    neededAtClosing: 78501,
    ioPayments: 23751,
    projectedSalePrice: 748000,
    projectedProfitFromSale: 64147,
    projectedProfitFromRehab: 28000,
    totalProjectedProfit: 92147,
    investedCapital: 48853,
    equityMultiple: 2.89,
    projectedCompletionDate: "2026-11-01",
    soldDate: null,
    soldPrice: null,
    notes: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prop_selma",
    address: "2828 Selma Avenue, Knoxville, TN 37914",
    stage: "under_contract",
    lender: "Tier 1 Capital",
    interestRate: 0.085,
    closingDate: "2026-04-15",
    sellerTitleCompany: "Good Deeds",
    buyerTitleCompany: "Good Deeds",
    purchasePrice: 135000,
    rehabBudget: 52400,
    earnestMoney: 1000,
    downPayment: 18700,
    totalLoanAmount: 168700,
    origFee: 844,
    loanFee: 1157,
    acquisitionFee: 6750,
    financeFee: 3374,
    closingCosts: 2531,
    neededAtClosing: 23231,
    ioPayments: 7072,
    projectedSalePrice: 225000,
    projectedProfitFromSale: 15874,
    projectedProfitFromRehab: 10480,
    totalProjectedProfit: 26354,
    investedCapital: 21726,
    equityMultiple: 2.21,
    projectedCompletionDate: "2026-10-01",
    soldDate: null,
    soldPrice: null,
    notes: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prop_skyline",
    address: "152 Skyline Lane, Powell, TN",
    stage: "under_contract",
    lender: null,
    interestRate: null,
    closingDate: "2026-05-20",
    sellerTitleCompany: "Pillar Title",
    buyerTitleCompany: "Good Deeds",
    purchasePrice: 65000,
    rehabBudget: null,
    earnestMoney: 6500,
    downPayment: null,
    totalLoanAmount: null,
    origFee: null,
    loanFee: null,
    acquisitionFee: 3250,
    financeFee: null,
    closingCosts: 975,
    neededAtClosing: 59475,
    ioPayments: null,
    projectedSalePrice: null,
    projectedProfitFromSale: null,
    projectedProfitFromRehab: null,
    totalProjectedProfit: null,
    investedCapital: 0,
    equityMultiple: null,
    projectedCompletionDate: null,
    soldDate: null,
    soldPrice: null,
    notes: "Incomplete underwriting — financing terms pending.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prop_augusta",
    address: "420 Augusta National Way, Knoxville, TN",
    stage: "under_contract",
    lender: null,
    interestRate: null,
    closingDate: "2026-06-15",
    sellerTitleCompany: null,
    buyerTitleCompany: "Good Deeds",
    purchasePrice: 500000,
    rehabBudget: null,
    earnestMoney: 5000,
    downPayment: null,
    totalLoanAmount: null,
    origFee: null,
    loanFee: null,
    acquisitionFee: 15000,
    financeFee: null,
    closingCosts: null,
    neededAtClosing: null,
    ioPayments: null,
    projectedSalePrice: 875000,
    projectedProfitFromSale: null,
    projectedProfitFromRehab: null,
    totalProjectedProfit: null,
    investedCapital: null,
    equityMultiple: null,
    projectedCompletionDate: null,
    soldDate: null,
    soldPrice: null,
    notes: "Underwriting in progress.",
    createdAt: now,
    updatedAt: now,
  },
];
